"""Summaries, printing and casting instructions, and file output for a generated mold."""

from __future__ import annotations

import io
import json
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING, Any

import numpy as np

from moldgen import __version__
from moldgen.meshio import export_mesh

if TYPE_CHECKING:
    from moldgen.pipeline import MoldResult

AXIS_NAMES = {0: "X", 1: "Y", 2: "Z"}


def _round(values: Any, digits: int = 2) -> Any:
    return np.round(np.asarray(values, dtype=float), digits).tolist()


def _direction_label(vector: np.ndarray) -> str:
    axis = int(np.argmax(np.abs(vector)))
    if abs(vector[axis]) > 0.999:
        return ("+" if vector[axis] > 0 else "-") + AXIS_NAMES[axis]
    return "(" + ", ".join(f"{v:.3f}" for v in vector) + ")"


def summary(result: MoldResult) -> dict[str, Any]:
    """JSON-serialisable description of the mold and the decisions behind it."""
    part = result.part.mesh
    block_size = result.block_bounds[1] - result.block_bounds[0]
    pieces = []
    for piece in result.pieces:
        volume_cm3 = float(piece.mesh.volume) / 1000.0
        pieces.append(
            {
                "name": piece.name,
                "volume_cm3": round(volume_cm3, 2),
                "approx_mass_g": round(volume_cm3 * result.print_material.density_g_cm3, 1),
                "print_size_mm": _round(piece.print_mesh().extents, 1),
            }
        )
    return {
        "moldgen_version": __version__,
        "created": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "part": {
            "name": result.part.name,
            "size_mm": _round(part.extents, 2),
            "volume_cm3": round(float(part.volume) / 1000.0, 3),
            "repair_actions": result.part.repair.actions,
        },
        "material": {
            "key": result.material.key,
            "name": result.material.name,
            "shrink_compensation_scale": round(result.shrink_scale, 5),
            "cast_volume_cm3": round(float(result.cavity.volume) / 1000.0, 3),
        },
        "print_material": {"key": result.print_material.key, "name": result.print_material.name},
        "parting": {
            "direction": _round(result.parting.direction, 4),
            "direction_label": _direction_label(result.parting.direction),
            "offset_mm": round(float(result.parting.offset), 3),
            "undercut_fraction": round(float(result.parting.undercut_fraction), 4),
            "low_draft_fraction": round(float(result.parting.low_draft_fraction), 4),
        },
        "mold": {
            "pieces": len(result.pieces),
            "wall_thickness_mm": round(result.wall_thickness, 2),
            "outer_size_mm": _round(block_size, 1),
            "pour_up_axis": _direction_label(result.gating.up),
            "sprue_diameter_mm": round(2 * result.gating.sprue.radius, 2),
            "funnel": result.gating.funnel is not None,
            "vents": len(result.gating.vents),
            "keys": int(sum(len(plan.positions) for plan in result.keys)),
            "key_clearance_mm": result.config.clearance,
        },
        "pieces": pieces,
        "warnings": list(result.warnings),
        "timings_s": {name: round(seconds, 3) for name, seconds in result.timings.items()},
        "config": result.config.to_dict(),
    }


def instructions(result: MoldResult) -> str:
    """Plain-text printing, assembly and casting instructions for this mold."""
    material = result.material
    printing = result.print_material
    info = summary(result)
    names = ", ".join(piece["name"] for piece in info["pieces"])
    lines = [
        f"Mold for {result.part.name} ({material.name})",
        f"Generated by moldgen {__version__}",
        "",
        "PRINTING",
        f"- Pieces: {names}. Each STL is already oriented with the parting face up,",
        "  so the cavity opens upwards and no supports are needed.",
        f"- Print material: {printing.name}.",
        "- Use at least 4 perimeters (or 100 % infill) so liquid cannot seep into the infill.",
        "- A layer height of 0.12-0.2 mm gives a smooth cavity; sand or coat it for a glossy cast.",
        "",
        "ASSEMBLY",
        "- Check that the registration keys seat fully before casting; lightly sand them if tight.",
        "- Clamp or tape the pieces firmly. For thin liquids, seal the outer seam with tape or clay.",
        f"- Apply release agent to the cavity: {material.release_agent}.",
        "",
        "POURING",
        f"- Stand the mold so the funnel faces up (the {info['mold']['pour_up_axis']} side of the "
        "mold block points up).",
        "- Pour slowly in a thin, steady stream into the funnel until material rises in the "
        "sprue and vents.",
    ]
    if result.gating.vents:
        lines.append(
            f"- {len(result.gating.vents)} air vent(s) let trapped air escape; keep them open."
        )
    if material.pour_temp_c is not None:
        low, high = material.pour_temp_c
        lines.append(f"- Typical pour temperature: {low:.0f}-{high:.0f} C.")
    if material.notes:
        lines.append(f"- {material.notes}")
    lines += [
        "",
        "DEMOLDING",
        "- Separate the pieces along the parting line; do not lever against the cavity edges.",
        "- Trim the sprue and vent stubs from the cast.",
    ]
    low_draft = result.parting.low_draft_fraction
    if low_draft > 0.05:
        lines.append(
            f"- {low_draft:.0%} of the surface has little or no draft; extra release agent helps."
        )
    if result.shrink_scale != 1.0:
        lines += [
            "",
            "SIZE",
            f"- The cavity is scaled by {result.shrink_scale:.4f} to compensate for "
            f"{material.name} shrinkage.",
        ]
    if result.warnings:
        lines += ["", "WARNINGS", *(f"- {warning}" for warning in result.warnings)]
    return "\n".join(lines) + "\n"


def save_result(result: MoldResult, out_dir: str | Path) -> list[Path]:
    """Write print-ready STL pieces, ``report.json`` and ``INSTRUCTIONS.txt``."""
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    written = []
    for piece in result.pieces:
        path = out / f"{result.part.name}_{piece.name}.stl"
        mesh = piece.print_mesh() if result.config.orient_for_print else piece.mesh
        written.append(export_mesh(mesh, path))
    report_path = out / "report.json"
    report_path.write_text(json.dumps(summary(result), indent=2) + "\n", encoding="utf-8")
    written.append(report_path)
    guide_path = out / "INSTRUCTIONS.txt"
    guide_path.write_text(instructions(result), encoding="utf-8")
    written.append(guide_path)
    return written


def zip_result(result: MoldResult) -> bytes:
    """All output files of :func:`save_result` as an in-memory zip archive."""
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for piece in result.pieces:
            mesh = piece.print_mesh() if result.config.orient_for_print else piece.mesh
            archive.writestr(f"{result.part.name}_{piece.name}.stl", mesh.export(file_type="stl"))
        archive.writestr("report.json", json.dumps(summary(result), indent=2) + "\n")
        archive.writestr("INSTRUCTIONS.txt", instructions(result))
    return buffer.getvalue()
